# build
FROM node:22-alpine AS build
WORKDIR /app
COPY curbonomix-app/curbonomix-frontend /app
RUN npm ci || npm install
RUN npm run build

# serve
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80