FROM python:3.11-slim
WORKDIR /app
COPY curbonomix-app/Curbonomix-backend /app
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000
CMD ["waitress-serve", "--listen=0.0.0.0:8000", "app:app"]