services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: curbonomix-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
    container_name: curbonomix-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped